services:
  sktorrent-hybrid:
    build: .
    container_name: sktorrent-hybrid
    restart: unless-stopped
    ports:
      - "127.0.0.1:7000:7000"
    environment:
      - REALDEBRID_API_KEY=${REALDEBRID_API_KEY}
      - SKT_UID=${SKT_UID}
      - SKT_PASS=${SKT_PASS}
      - ADDON_API_KEY=${ADDON_API_KEY}
      - STREAM_MODE=${STREAM_MODE}
      - NODE_ENV=production
      - EXTERNAL_DOMAIN=${EXTERNAL_DOMAIN}
    env_file:
      - .env